/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP I5
 */
public class ventanacalculadora extends javax.swing.JFrame {

    String cadenaNumeros ="";
    private double numero1,resultadoOperacion;
    private String operacion = "nula";
private boolean activado =true;
private boolean punto = true;
    
    
    public ventanacalculadora() {
        initComponents();
        setSize(300,450);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel2 = new javax.swing.JPanel();
        C = new javax.swing.JButton();
        Raizcuadrada = new javax.swing.JButton();
        Dividir = new javax.swing.JButton();
        Eliminar = new javax.swing.JButton();
        Etiqueta_numeros = new javax.swing.JLabel();
        Etiqueta_muestra = new javax.swing.JLabel();
        resultados = new javax.swing.JLabel();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonX = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        botonmenos = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonmas = new javax.swing.JButton();
        botonmasmenos = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonpunto = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        Menu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Calculadora_estandar = new javax.swing.JMenuItem();
        Divisa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");
        setSize(new java.awt.Dimension(300, 450));

        jPanel2.setLayout(new java.awt.GridBagLayout());

        C.setBackground(new java.awt.Color(255, 153, 51));
        C.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        C.setText("C");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(C, gridBagConstraints);

        Raizcuadrada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/raiz cuadrada.png"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(Raizcuadrada, gridBagConstraints);

        Dividir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/dividir.jpg"))); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(Dividir, gridBagConstraints);

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/borrar.png"))); // NOI18N
        Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(Eliminar, gridBagConstraints);

        Etiqueta_numeros.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        Etiqueta_numeros.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Etiqueta_numeros.setText("0");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(Etiqueta_numeros, gridBagConstraints);
        jPanel2.add(Etiqueta_muestra, new java.awt.GridBagConstraints());

        resultados.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        resultados.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        resultados.setText("  ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(resultados, gridBagConstraints);

        boton7.setBackground(new java.awt.Color(0, 255, 153));
        boton7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton7, gridBagConstraints);

        boton8.setBackground(new java.awt.Color(0, 255, 153));
        boton8.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton8, gridBagConstraints);

        boton9.setBackground(new java.awt.Color(0, 255, 153));
        boton9.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton9, gridBagConstraints);

        botonX.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonX.setText("X");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonX, gridBagConstraints);

        boton4.setBackground(new java.awt.Color(0, 255, 153));
        boton4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton4, gridBagConstraints);

        boton5.setBackground(new java.awt.Color(0, 255, 153));
        boton5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton5, gridBagConstraints);

        boton6.setBackground(new java.awt.Color(0, 255, 153));
        boton6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton6, gridBagConstraints);

        botonmenos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonmenos.setText("-");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonmenos, gridBagConstraints);

        boton1.setBackground(new java.awt.Color(0, 255, 153));
        boton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton1, gridBagConstraints);

        boton2.setBackground(new java.awt.Color(0, 255, 153));
        boton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton2, gridBagConstraints);

        boton3.setBackground(new java.awt.Color(0, 255, 153));
        boton3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton3, gridBagConstraints);

        botonmas.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonmas.setText("+");
        botonmas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonmas, gridBagConstraints);

        botonmasmenos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/mas menos.png"))); // NOI18N
        botonmasmenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmasmenosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonmasmenos, gridBagConstraints);

        boton0.setBackground(new java.awt.Color(0, 255, 153));
        boton0.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(boton0, gridBagConstraints);

        botonpunto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonpunto.setText(".");
        botonpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonpuntoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonpunto, gridBagConstraints);

        botonIgual.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botonIgual.setText("=");
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 0.5;
        jPanel2.add(botonIgual, gridBagConstraints);

        menu.setText("Usos");
        menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        Calculadora_estandar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Calculadora_estandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/calculadora.png"))); // NOI18N
        Calculadora_estandar.setText("Calculadora estandar");
        menu.add(Calculadora_estandar);

        Divisa.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Divisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/divisas.png"))); // NOI18N
        Divisa.setText("Conversor de divisas");
        Divisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisaActionPerformed(evt);
            }
        });
        menu.add(Divisa);
        menu.add(jSeparator1);

        Salir.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/salir.jpg"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        menu.add(Salir);

        Menu.add(menu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
     System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void DivisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisaActionPerformed
ventanaDivisas conversor = new ventanaDivisas ();
conversor.setVisible(true);
dispose ();
    }//GEN-LAST:event_DivisaActionPerformed

    private void EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarActionPerformed
int tamaño = cadenaNumeros.length();
if(tamaño>0){
    if(tamaño ==1){
        cadenaNumeros ="0";
        
    }
    cadenaNumeros = cadenaNumeros.substring(0,cadenaNumeros.length() -1);
    Etiqueta_numeros.setText(cadenaNumeros);
    
    
    
}
        
        
        
    }//GEN-LAST:event_EliminarActionPerformed
 
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton1ActionPerformed
cadenaNumeros += "1";
Etiqueta_numeros.setText(cadenaNumeros);
    activado =true;

    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton2ActionPerformed
  cadenaNumeros += "2";
  Etiqueta_numeros.setText(cadenaNumeros);
      activado =true;

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton3ActionPerformed
cadenaNumeros  += "3";
Etiqueta_numeros.setText(cadenaNumeros);
    activado =true;


    }//GEN-LAST:event_boton3ActionPerformed

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton4ActionPerformed
    
    cadenaNumeros += "4";
    Etiqueta_numeros.setText(cadenaNumeros);
        activado =true;

    }//GEN-LAST:event_boton4ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton5ActionPerformed
  cadenaNumeros += "5";
    Etiqueta_numeros.setText(cadenaNumeros);
        activado =true;

    }//GEN-LAST:event_boton5ActionPerformed

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton6ActionPerformed
       cadenaNumeros += "6";
    Etiqueta_numeros.setText(cadenaNumeros);
        activado =true;

    }//GEN-LAST:event_boton6ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton7ActionPerformed
        cadenaNumeros += "7";
    Etiqueta_numeros.setText(cadenaNumeros);
        activado =true;

    
    }//GEN-LAST:event_boton7ActionPerformed

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton8ActionPerformed
  cadenaNumeros += "8";
    Etiqueta_numeros.setText(cadenaNumeros);
    activado =true;
    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton9ActionPerformed
  cadenaNumeros += "9";
    Etiqueta_numeros.setText(cadenaNumeros);
    activado =true;
    }//GEN-LAST:event_boton9ActionPerformed

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton0ActionPerformed
    if(cadenaNumeros !=""){
    cadenaNumeros += "0";
    Etiqueta_numeros.setText(cadenaNumeros);
    activado =true;
        
    }
    }//GEN-LAST:event_boton0ActionPerformed

    private void botonmasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasActionPerformed
if(activado==true){
        numero1= Double.parseDouble(cadenaNumeros);
        cadenaNumeros = "";
        resultados.setText(numero1 +  " + ");
        operacion = "sumar";
        activado = false;
        punto = true; 
}
    }//GEN-LAST:event_botonmasActionPerformed

    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIgualActionPerformed
    activado =true;
operacion = "nula";
  
double numero2;
if(operacion.equals("nula")){
    Etiqueta_numeros.setText(cadenaNumeros);
}
else if(operacion.equals("sumar")){
    numero2 = Double.parseDouble(cadenaNumeros);
    resultadoOperacion = numero1 + numero2;
    Etiqueta_numeros.setText(String.format ("%.2f",resultadoOperacion));
cadenaNumeros= String.valueOf(resultadoOperacion);
}
  resultados.setText(""); 
    }//GEN-LAST:event_botonIgualActionPerformed

    private void botonpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonpuntoActionPerformed
if(punto == true){
  if(cadenaNumeros == ""){
           cadenaNumeros ="0.";}
        

    else {
        cadenaNumeros += ".";

}
        
punto = false;
}
Etiqueta_numeros.setText(cadenaNumeros); 
    }//GEN-LAST:event_botonpuntoActionPerformed

    private void botonmasmenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmasmenosActionPerformed
   if(cadenaNumeros.charAt(0) != '-'){
       cadenaNumeros = "-"+ cadenaNumeros;
   }
   else {
       cadenaNumeros = cadenaNumeros.substring(1,cadenaNumeros.length());   
   }     
Etiqueta_numeros.setText(cadenaNumeros);        
        
        
    }//GEN-LAST:event_botonmasmenosActionPerformed
      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (ClassNotFoundException ex) {
           // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
         //    Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
         
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanacalculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton C;
    private javax.swing.JMenuItem Calculadora_estandar;
    private javax.swing.JButton Dividir;
    private javax.swing.JMenuItem Divisa;
    private javax.swing.JButton Eliminar;
    private javax.swing.JLabel Etiqueta_muestra;
    private javax.swing.JLabel Etiqueta_numeros;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JButton Raizcuadrada;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonX;
    private javax.swing.JButton botonmas;
    private javax.swing.JButton botonmasmenos;
    private javax.swing.JButton botonmenos;
    private javax.swing.JButton botonpunto;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu;
    private javax.swing.JLabel resultados;
    // End of variables declaration//GEN-END:variables
}
