/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author HP I5
 */
public class ventanaDivisas extends javax.swing.JFrame {

    /**
     * Creates new form ventanaDivisas
     */
    public ventanaDivisas() {
        initComponents();
        setSize(300,450);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Menu = new javax.swing.JMenuBar();
        menu = new javax.swing.JMenu();
        Calculadora_estandar = new javax.swing.JMenuItem();
        Divisa = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversos de divisas");

        menu.setText("Usos");
        menu.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N

        Calculadora_estandar.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Calculadora_estandar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/calculadora.png"))); // NOI18N
        Calculadora_estandar.setText("Calculadora estandar");
        Calculadora_estandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calculadora_estandarActionPerformed(evt);
            }
        });
        menu.add(Calculadora_estandar);

        Divisa.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Divisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/divisas.png"))); // NOI18N
        Divisa.setText("Conversor de divisas");
        menu.add(Divisa);
        menu.add(jSeparator1);

        Salir.setFont(new java.awt.Font("Arial Narrow", 1, 14)); // NOI18N
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagene/salir.jpg"))); // NOI18N
        Salir.setText("Salir");
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        menu.add(Salir);

        Menu.add(menu);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_SalirActionPerformed

    private void Calculadora_estandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calculadora_estandarActionPerformed
 ventanacalculadora calculadora = new ventanacalculadora ();
 calculadora.setVisible(true);
 dispose (); 
    }//GEN-LAST:event_Calculadora_estandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
           try {
            UIManager.setLookAndFeel("com.jtattoo.plaf.texture.TextureLookAndFeel");
        } catch (ClassNotFoundException ex) {
           // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            // Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
         //    Logger.getLogger(ventanacalculadora.class.getName()).log(Level.SEVERE, null, ex);
        }
        
 
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ventanaDivisas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Calculadora_estandar;
    private javax.swing.JMenuItem Divisa;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenuItem Salir;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu menu;
    // End of variables declaration//GEN-END:variables
}
